// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRU1CpW48XknZijLUuK2DSpJnud5tM6Sc',
    appId: '1:928498423530:web:75a4a27e6e0e27cec8e993',
    messagingSenderId: '928498423530',
    projectId: 'belfort-68356',
    authDomain: 'belfort-68356.firebaseapp.com',
    storageBucket: 'belfort-68356.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFxYereXa5K9kkEvX8yh7K0wAzGYlK7s',
    appId: '1:928498423530:android:ce488a9b081e2ab8c8e993',
    messagingSenderId: '928498423530',
    projectId: 'belfort-68356',
    storageBucket: 'belfort-68356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxf-NQJWQDxC92-wI8X6wOdBNxZPNUWs',
    appId: '1:928498423530:ios:244c92fe60c42487c8e993',
    messagingSenderId: '928498423530',
    projectId: 'belfort-68356',
    storageBucket: 'belfort-68356.firebasestorage.app',
    iosBundleId: 'com.example.belfort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuxf-NQJWQDxC92-wI8X6wOdBNxZPNUWs',
    appId: '1:928498423530:ios:244c92fe60c42487c8e993',
    messagingSenderId: '928498423530',
    projectId: 'belfort-68356',
    storageBucket: 'belfort-68356.firebasestorage.app',
    iosBundleId: 'com.example.belfort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRU1CpW48XknZijLUuK2DSpJnud5tM6Sc',
    appId: '1:928498423530:web:d659f380e1780c47c8e993',
    messagingSenderId: '928498423530',
    projectId: 'belfort-68356',
    authDomain: 'belfort-68356.firebaseapp.com',
    storageBucket: 'belfort-68356.firebasestorage.app',
  );
}
